name: poc-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  # conda dependencies
  - tensorflow
  - opencv
  - pandas
  - numpy
  - pillow
  - scipy
  - openpyxl

  # pip dependencies
  - pip:
      - fastapi
      - uvicorn[standard]
      - redis
      - pydantic
      - scikit-image
      - matplotlib
      - python-multipart
